travis: pypi check: do not explicitly list numpy as conda dep
Conda has problems solving the dependency graph:

    Solving environment: ...working... WARNING conda.core.solve:_add_specs(600):
    pinned spec numpy=stable conflicts with explicit specs.  Overriding pinned spec.

    PackagesNotFoundError: The following packages are not available from current channels:
    - numpy[version='1.18.*,stable.*']

Use ci-helper's algorithm for installing numpy.